### ISSUE TITLE
Tried looking at this, but build fails because of some hardcoded links

### ISSUE THREAD

**Issue by sg-s** [teckism/UserListCoreData#1]
error: Build input files cannot be found: '/Users/pankajteckchandani/Documents/StockList/StockList/Common/Blacklisted+CoreDataProperties.swift', '/Users/pankajteckchandani/Documents/StockList/StockList/Common/User+CoreDataProperties.swift', '/Users/pankajteckchandani/Documents/StockList/StockList/Common/User+CoreDataClass.swift', '/Users/pankajteckchandani/Documents/StockList/StockList/Common/Blacklisted+CoreDataClass.swift' (in target 'StockList' from project 'StockList')

**Comment by teckism** [comment]
PFA

**Comment by sg-s** [comment]
I'm sorry, what?

**Comment by teckism** [comment]
I have attached the entire project in the mail

**Comment by teckism** [comment]
oops, i replied it via email and attached the entire project hence the confusion.

**Comment by sg-s** [comment]
Yeah, sorry, I don't think replying via email allows you to attach things in github comments...

**Comment by teckism** [comment]
Can you verify it now

**Comment by sg-s** [comment]
Great! That issue is fixed, but now it can't find "SDWebImage" -- I think I need some 3rd part code. Thanks for the help -- I'll see how I can get this now

**Comment by teckism** [comment]
SDWebImage is a library, you will need to run pod install to update the library

**Comment by sg-s** [comment]
Thanks!
